name: Auto PR from Feature Branch to Develop

on:
  push:
    branches: # Bu Workflow'u sadece develop dışında herhangi bir branch'e push yapıldığında çalıştır
      - '**' # Herhangi bir branch için çalışır
      - '!develop' # Ancak develop branch'ini hariç tutar
      - '!master'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Create Pull Request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: ${{ github.ref_name }}
        destination_branch: develop
        pr_title: 'Auto PR: ${{ github.ref_name }} -> develop'
        pr_body: 'This pull request was automatically created by GitHub Actions.'
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
