name: Auto Label Pull Request Based on Branch Name

on:
  pull_request:
    types: [opened] # Sadece PR açıldığında çalıştırılır

jobs:
  label-based-on-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Add Label Based on Branch Name
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        if [[ "${{ github.head_ref }}" == *"feature/"* ]]; then
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels \
            -d '{"labels": ["feature"]}'
        elif [[ "${{ github.head_ref }}" == *"hotfix/"* ]]; then
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels \
            -d '{"labels": ["hotfix"]}'
        fi